### ISSUE TITLE
Is the Azure OpenAI Service Introductory Hands-on Lab available for commercial use?

### ISSUE THREAD

**Issue by twinparadox5820** [dev-lab-io/aoai-handson-src#1]
Can I use the following hands-on texts for commercial purposes?

https://dev-lab-io.github.io/aoai/scenario1/home

**Comment by k-in** [comment]
@twinparadox5820 
Hands-on content cannot be used for commercial purposes.

The source code of the demo application used in the hands-on can be used as OSS. However, neither I nor Microsoft take any responsibility for that source code.

**Comment by twinparadox5820** [comment]
Closed due to understanding
